### ISSUE TITLE
where are the python files?

### ISSUE THREAD

**Issue by kunyao2015** [SunYangtian/Neural-Human-Video-Rendering#1]
Nice job！but where are the train files(train.py,...)?

**Comment by SunYangtian** [comment]
Hi, we have released the code with another deep learning framework Jittor. Please refer to this  [link](https://github.com/IGLICT/DynamicHumanGeneration_Jittor). 

I will also organize the pytorch code soon.

**Comment by kunyao2015** [comment]
Thanks for your reply, I stared the new framework, close this issue

**Comment by zhangxujinsh** [comment]
@SunYangtian   looking forward to the pytorch code.  Thank you !
